apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dotnet-app
  namespace: prod
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: dotnet-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s